version: '3'

services:

  web:
      image: nginx:latest 
      networks:
      - local-dev-net
      volumes:
        - ./nginx/mysite.template:/etc/nginx/conf.d/mysite.template
        - ./code:/var/www/html/code
        - ./logs:/var/log/nginx
        - ./nginx/fastcgi.conf:/etc/nginx/fastcgi.conf
        - ./nginx/rewrite.conf:/etc/nginx/rewrite.conf
      ports:
        - "80:80"
      links:
        - php7
      extra_hosts:
        - "test.loc:127.0.0.1"
      command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && nginx-debug -g 'daemon off;'"

  php7:
#      build: ./php56/
      build: ./php72/
      networks:
      - local-dev-net
      volumes:
        - ./code:/var/www/html/code
      extra_hosts:
        - "test.loc:127.0.0.1"
      links:
           - mysql
      environment:
        XDEBUG_CONFIG: "remote_host=172.17.0.1"
        PHP_IDE_CONFIG: "serverName=Test"
        VIRTUAL_HOST: "test.loc"

  mariadb-data:
      image: tianon/true
      volumes:
          - ./mysql-data:/var/lib/mysql

  mysql:
      networks:
       - local-dev-net
      image: mariadb:latest
      expose:
          - 3306
      volumes:
          - ./mysql:/var/lib/mysql
      environment:
          MYSQL_ROOT_PASSWORD: 123
          MYSQL_DATABASE: abbott_new
          MYSQL_USER: abbott
          MYSQL_PASSWORD: 123

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql
    ports:
      - 8181:80
    networks:
      - local-dev-net
    environment:
      PMA_HOST: mysql

  mailhog:
    image: mailhog/mailhog:v1.0.0
    networks:
      - local-dev-net
    ports:
      - "1025:1025"
      - "8025:8025"
networks:
  local-dev-net:
    driver: bridge
